# Generated by Django 4.2 on 2025-12-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingitem',
            old_name='source_of_recepit',
            new_name='source_of_receipt',
        ),
    ]
