# Generated by Django 4.2 on 2025-12-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0002_rename_source_of_recepit_billingitem_source_of_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingItem',
        ),
    ]
