# Generated by Django 4.2 on 2025-12-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billsystem', '0003_delete_billingitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=255)),
                ('component', models.CharField(max_length=255)),
                ('investment_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=100)),
                ('allocated_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_of_receipt', models.CharField(max_length=255)),
                ('scheme_name', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'billing_2025_26',
            },
        ),
    ]
