# Generated by Django 4.2 on 2025-12-12 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0005_reguser_billingitem_updated_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
