# Generated by Django 4.2 on 2025-12-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0006_billingitem_created_at_billingitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitem',
            name='center_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='user_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
