# Generated by Django 4.2 on 2025-12-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0007_billingitem_center_id_billingitem_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitem',
            name='center_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='component',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
