# Generated by Django 4.2 on 2025-12-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0008_alter_billingitem_center_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitem',
            name='bill_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
