# Generated by Django 4.2 on 2025-12-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0009_billingitem_bill_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(blank=True, max_length=10)),
                ('center_id', models.CharField(blank=True, max_length=20)),
                ('user_id', models.CharField(blank=True, max_length=20)),
                ('center_name', models.CharField(blank=True, max_length=255, null=True)),
                ('component', models.CharField(blank=True, max_length=255, null=True)),
                ('investment_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=100)),
                ('allocated_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('source_of_receipt', models.CharField(max_length=255)),
                ('scheme_name', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billingreport_2025_26',
            },
        ),
    ]
