# Generated by Django 4.2 on 2025-12-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0010_billingreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingreport',
            name='allocated_quantity',
        ),
        migrations.RemoveField(
            model_name='billingreport',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='billingreport',
            name='component',
        ),
        migrations.RemoveField(
            model_name='billingreport',
            name='investment_name',
        ),
        migrations.RemoveField(
            model_name='billingreport',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='billingreport',
            name='scheme_name',
        ),
        migrations.RemoveField(
            model_name='billingreport',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='billingreport',
            name='updated_quantity',
        ),
        migrations.AddField(
            model_name='billingreport',
            name='bill_report_id',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='billingreport',
            name='component_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
