# Generated by Django 4.2 on 2025-12-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0011_remove_billingreport_allocated_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingreport',
            name='recipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='billingreport',
            name='status',
            field=models.CharField(default='accepted', max_length=50),
        ),
    ]
