# Generated by Django 4.2 on 2025-12-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0012_billingreport_recipt_file_billingreport_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterComponentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.CharField(blank=True, max_length=20)),
                ('user_id', models.CharField(blank=True, max_length=20)),
                ('source_of_receipt', models.CharField(max_length=255)),
                ('center_name', models.CharField(blank=True, max_length=255, null=True)),
                ('component', models.CharField(blank=True, max_length=255, null=True)),
                ('investment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(max_length=100)),
                ('scheme_name', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'center_component_details',
                'unique_together': {('center_id', 'component', 'investment_name')},
            },
        ),
    ]
