# Generated by Django 4.2 on 2025-12-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0014_scheme_componentinvestment'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentinvestment',
            name='unit',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
