# Generated by Django 4.2 on 2025-12-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0015_componentinvestment_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingreport',
            name='billing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
