# Generated by Django 4.2 on 2025-12-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0016_billingreport_billing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('farmer_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('block_name', models.CharField(max_length=255)),
                ('assembly_name', models.CharField(max_length=255)),
                ('center_name', models.CharField(max_length=255)),
                ('supplied_item_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aadhaar_number', models.CharField(max_length=20)),
                ('bank_account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=100)),
                ('scheme_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
