# Generated by Django 4.2 on 2025-12-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0017_beneficiaryregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='VikasKhandVidhanSabha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vikas_khand_name', models.CharField(max_length=255)),
                ('vidhan_sabha_name', models.CharField(max_length=255)),
                ('center_name', models.CharField(max_length=255)),
            ],
        ),
    ]
