# Generated by Django 4.2 on 2025-12-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0018_vikaskhandvidhansabha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiaryregistration',
            name='assembly_name',
        ),
        migrations.RemoveField(
            model_name='beneficiaryregistration',
            name='block_name',
        ),
        migrations.AddField(
            model_name='beneficiaryregistration',
            name='vidhan_sabha_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='beneficiaryregistration',
            name='vikas_khand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='vidhan_sabha_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='vikas_khand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
