# Generated by Django 4.2 on 2025-12-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0019_remove_beneficiaryregistration_assembly_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitem',
            name='sub_investment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
