# Generated by Django 4.2 on 2025-12-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0020_billingitem_sub_investment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitem',
            name='investment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='source_of_receipt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
