# Generated by Django 4.2 on 2025-12-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0021_alter_billingitem_investment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingitem',
            name='scheme_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
