# Generated by Django 4.2 on 2025-12-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0022_alter_billingitem_scheme_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='componentinvestment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='componentinvestment',
            name='sub_investment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='componentinvestment',
            name='component',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='componentinvestment',
            name='investment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='componentinvestment',
            unique_together={('component', 'investment_name', 'sub_investment_name')},
        ),
    ]
