# Generated by Django 4.2 on 2025-12-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0023_alter_componentinvestment_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryRegistrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_id', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=10)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=20)),
                ('action', models.CharField(choices=[('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=10)),
                ('old_data', models.JSONField(blank=True, null=True)),
                ('new_data', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_item_log',
            },
        ),
    ]
