# Generated by Django 4.2 on 2025-12-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0024_beneficiaryregistrationlog_billingitemlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiaryregistrationlog',
            name='new_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiaryregistrationlog',
            name='old_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingitemlog',
            name='new_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingitemlog',
            name='old_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
