# Generated by Django 4.2 on 2026-01-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0025_alter_beneficiaryregistrationlog_new_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryregistrationlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingitemlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
