# Generated by Django 4.2 on 2026-01-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0026_beneficiaryregistrationlog_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingitem',
            name='component',
        ),
        migrations.AddField(
            model_name='billingitem',
            name='amount_of_farmer_share',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='amount_of_subsidy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billingitem',
            name='scheme_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
