# Generated by Django 4.2 on 2026-01-13 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0027_remove_billingitem_component_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='componentinvestment',
            unique_together={('investment_name', 'sub_investment_name')},
        ),
        migrations.RemoveField(
            model_name='componentinvestment',
            name='component',
        ),
    ]
