# Generated by Django 4.2 on 2026-01-14 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0028_alter_componentinvestment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reguser',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reguser',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reguser',
            name='user_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reguser',
            name='username',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
