# Generated by Django 4.2 on 2026-01-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0029_reguser_created_at_reguser_role_reguser_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegUserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=10)),
                ('old_data', models.TextField(blank=True, null=True)),
                ('new_data', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
