# Generated by Django 4.2 on 2026-01-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0030_reguseractionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reguseractionlog',
            name='action',
            field=models.CharField(max_length=80),
        ),
    ]
