# Generated by Django 4.2 on 2026-01-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0031_alter_reguseractionlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_id', models.CharField(max_length=20)),
                ('center_name', models.CharField(max_length=255)),
                ('demand_list', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demand_generation',
            },
        ),
    ]
