# Generated by Django 4.2 on 2026-01-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0032_demandgeneration'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingitem',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
