# Generated by Django 4.2 on 2026-01-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0033_billingitem_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryregistration',
            name='beneficiary_reg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
