# Generated by Django 4.2 on 2026-01-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0034_beneficiaryregistration_beneficiary_reg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingreport',
            name='source_of_receipt',
        ),
        migrations.RemoveField(
            model_name='billingreport',
            name='user_id',
        ),
    ]
