# Generated by Django 4.2 on 2026-01-31 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0035_remove_billingreport_source_of_receipt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemandGeneration',
        ),
    ]
