# Generated by Django 4.2 on 2026-01-31 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0036_delete_demandgeneration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('sub_investment_name', models.CharField(blank=True, max_length=255, null=True)),
                ('allocated_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'demand_generation',
            },
        ),
        migrations.CreateModel(
            name='DemandByCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=255)),
                ('demanded_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('demand_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demand_centers', to='billsystem.demandgeneration', to_field='demand_id')),
            ],
            options={
                'db_table': 'demand_by_center',
            },
        ),
    ]
