# Generated by Django 4.2 on 2026-02-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0037_demandgeneration_demandbycenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandgeneration',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
