# Generated by Django 4.2 on 2026-02-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0038_demandgeneration_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandByCenterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_id', models.CharField(max_length=30)),
                ('center_name', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('DELETE', 'DELETE')], max_length=10)),
                ('old_data', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demand_by_center_log',
            },
        ),
        migrations.CreateModel(
            name='DemandGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_id', models.CharField(max_length=30)),
                ('action', models.CharField(choices=[('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=10)),
                ('old_data', models.TextField(blank=True, null=True)),
                ('new_data', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'demand_generation_log',
            },
        ),
    ]
