# Generated by Django 4.2 on 2026-02-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0039_demandbycenterlog_demandgenerationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandbycenterlog',
            name='new_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandbycenterlog',
            name='action',
            field=models.CharField(choices=[('DELETE', 'DELETE'), ('UPDATE', 'UPDATE')], max_length=10),
        ),
    ]
