# Generated by Django 4.2 on 2026-02-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0041_nurseryfinancial_nurseryfinanciallog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurseryfinanciallog',
            old_name='created_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='nurseryfinanciallog',
            name='nursery_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nurseryfinanciallog',
            name='action',
            field=models.CharField(choices=[('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=10),
        ),
        migrations.AlterField(
            model_name='nurseryfinanciallog',
            name='new_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nurseryfinanciallog',
            name='old_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='nurseryfinanciallog',
            table='nursery_financial_log',
        ),
    ]
