# Generated by Django 4.2 on 2026-02-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0042_rename_created_at_nurseryfinanciallog_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nurseryfinanciallog',
            table=None,
        ),
    ]
