# Generated by Django 4.2 on 2026-02-11 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0043_alter_nurseryfinanciallog_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nurseryfinancial',
            name='unit',
        ),
    ]
