# Generated by Django 4.2 on 2026-02-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0044_remove_nurseryfinancial_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurseryfinancial',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
