# Generated by Django 4.2 on 2026-02-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billsystem', '0045_nurseryfinancial_registration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseryPhysical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nursery_name', models.CharField(blank=True, max_length=255, null=True)),
                ('crop_name', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=100)),
                ('allocated_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'production',
            },
        ),
        migrations.CreateModel(
            name='NurseryPhysicalRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recipient_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill_number', models.CharField(blank=True, max_length=20, null=True)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nursery_physical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='billsystem.nurseryphysical')),
            ],
            options={
                'db_table': 'production_recipient',
            },
        ),
    ]
